version: '3.4'

services:
  myfirstproject:
    image: ${DOCKER_REGISTRY-}myfirstproject
    build:
      context: .
      dockerfile: MyFirstProject/Dockerfile
 
  db:
    image: postgres
    restart: always
    ports:  
    - "5433:5432"
    # set shared memory limit when using docker-compose
    #shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes: "/var/lib/postgresql/data"
    #  - type: tmpfs
         #/var/lib/postgresql/data 
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: my_notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres